dist: xenial
language: csharp
mono: none
dotnet: 2.2.204
script:
- dotnet restore
- dotnet test
deploy:
  skip_cleanup: true
  - provider: script
    script: bash deploy.sh $TRAVIS_TAG $NUGET_API_KEY
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+